# Generated by Django 4.1.5 on 2023-01-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="gender",
            field=models.CharField(
                choices=[("Laki-laki", "male"), ("Perempuan", "female")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="relation_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="family_app.optionfamily",
            ),
        ),
    ]
