# Generated by Django 4.1.5 on 2023-01-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0004_optioncity_optioncountry_alter_optionfamily_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionfamily", name="fid", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="optionfamily", name="idf", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="optionfamily", name="mid", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="optionfamily",
            name="pids",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="optionfamily",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
