# Generated by Django 4.1.5 on 2023-01-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "family_app",
            "0005_optionfamily_fid_optionfamily_idf_optionfamily_mid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionfamily",
            name="fid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="optionfamily",
            name="mid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
