# Generated by Django 4.1.5 on 2023-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0006_alter_optionfamily_fid_alter_optionfamily_mid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="fid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="mid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="pids",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
