# Generated by Django 4.1.5 on 2023-01-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0007_alter_family_fid_alter_family_mid_alter_family_pids"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="photo",
            field=models.ImageField(null=True, upload_to="profil"),
        ),
    ]
