# Generated by Django 4.1.5 on 2023-01-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0008_family_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="family", name="death", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="family", name="born", field=models.DateField(null=True),
        ),
    ]
