# Generated by Django 4.1.5 on 2023-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0009_family_death_alter_family_born"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
