# Generated by Django 4.1.5 on 2023-01-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0010_alter_family_city_alter_family_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("suami", "suami"),
                    ("istri", "istri"),
                    ("anak perempuan", "anak perempuan"),
                    ("anak laki-laki", "anak laki-laki"),
                    ("ayah", "ayah"),
                    ("ibu", "ibu"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="relation_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="family_app.optionfamily",
            ),
        ),
    ]
