# Generated by Django 4.1.5 on 2023-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0011_alter_family_relation_alter_family_relation_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="relation_from",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
