# Generated by Django 4.1.5 on 2023-01-31 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0012_alter_family_relation_from"),
    ]

    operations = [
        migrations.RemoveField(model_name="family", name="relation_from",),
    ]
