# Generated by Django 4.1 on 2023-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_app', '0013_remove_family_relation_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionFamily',
        ),
    ]
