# Generated by Django 4.1.5 on 2023-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_app", "0016_alter_family_pids_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profil",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
